# Generated by Django 3.2.7 on 2021-09-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='id',
        ),
        migrations.AlterField(
            model_name='bids',
            name='tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bids', serialize=False, to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='comments', serialize=False, to='auctions.listings'),
        ),
    ]
