# Generated by Django 3.2.7 on 2021-09-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210916_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title_id',
        ),
        migrations.DeleteModel(
            name='bids',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.DeleteModel(
            name='listings',
        ),
    ]
