# Generated by Django 3.2.7 on 2021-09-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.CharField(default='No Describtion out there', max_length=411),
        ),
    ]
