# Generated by Django 3.2.7 on 2021-09-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, default='sabo.png', upload_to='auctions/static/auctions/images'),
        ),
    ]
