# Generated by Django 3.2.7 on 2021-09-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='current_bid',
            field=models.IntegerField(default=models.IntegerField(default=1)),
        ),
    ]
