# Generated by Django 3.2.7 on 2021-09-26 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_remove_listings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='owner',
            field=models.ForeignKey(default='mohamed_hashim', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
